from hw8.laitz82 import *
from hw8.score import score
s = import_score("C:/Users/qwert/School/MUS105/kjzhou2/hw8/xmls/Laitz_p84A.musicxml")
s2 = import_score("C:/Users/qwert/School/MUS105/kjzhou2/hw8/xmls/Laitz_p84B.musicxml")
s3 = import_score("C:/Users/qwert/School/MUS105/kjzhou2/hw8/xmls/Laitz_p84C.musicxml")
s4 = import_score("C:/Users/qwert/School/MUS105/kjzhou2/hw8/xmls/Laitz_p84D.musicxml")
s5 = import_score("C:/Users/qwert/School/MUS105/kjzhou2/hw8/xmls/Laitz_p84E.musicxml")
s6 = import_score("C:/Users/qwert/School/MUS105/kjzhou2/hw8/xmls/Laitz_p84F.musicxml")
s7 = import_score("C:/Users/qwert/School/MUS105/kjzhou2/hw8/xmls/Laitz_p84G.musicxml")
# a = MelodicAnalysis(s)
# print("A")
# print(a.submit_to_grading())
# a = MelodicAnalysis(s2)
# print("B")
# print(a.submit_to_grading())
# a = MelodicAnalysis(s3)
# print("C")
# print(a.submit_to_grading())
# a = MelodicAnalysis(s4)
# print("D")
# print(a.submit_to_grading())
a = MelodicAnalysis(s5)
print("E")
print(a.submit_to_grading())
# a = MelodicAnalysis(s6)
# print("F")
# print(a.submit_to_grading())
# a = MelodicAnalysis(s7)
# print("G")
# print(a.submit_to_grading())